server:
  port: 8080
spring:
  application:
    name: eureka-client-a
#security:
#  basic:
#    enabled: true
#  user:
#    name: client-a
#    password: 123456
#discovery-username: leekoy
#discovery-password: 123456
eureka:
  instance:
    status-page-url-path: /info
    health-check-url-path: /health
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
#      defaultZone: http://${discovery-username}:${discovery-password}@192.168.136.130:8761/eureka/
       defaultZone: http://test1:8081/eureka/
    healthcheck:
      enabled: true
feign:
  hystrix:
    enabled: true