server:
  port: 8080
discovery-username: leekoy
discovery-password: 123456
#security:
#  basic:
#    enabled: true
#  user:
#    name: server-a
#    password: 123456
eureka:
  instance:
    status-page-url-path: /info
    health-check-url-path: /health
    hostname: localhost
  client:
    service-url:
#      defaultZone: http://${discovery-username}:${discovery-password}@192.168.136.130:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
spring:
  application:
    name: eureka-server-a